- name: Installs zsh
  become: true
  ansible.builtin.dnf:
    name: zsh
    state: present

- name: Installs antigen
  ansible.builtin.get_url:
    url: http://git.io/antigen
    dest: "{{ user_home }}/.antigen.zsh"
    mode: u=rwx

- name: Check if zshrc exists
  ansible.builtin.stat:
    path: "{{ user_home }}/.zshrc"
  register: zshrc_stat
  failed_when: false

- name: Backup zshrc
  ansible.builtin.command: mv {{ user_home }}/.zshrc {{ user_home }}/.zshrc.bak
  when: zshrc_stat.stat.exists
  changed_when: false

- name: Symlink .zshrc
  ansible.builtin.file:
    src: "{{ role_path }}/files/.zshrc"
    dest: "{{ user_home }}/.zshrc"
    state: link
    mode: u=rwx

- name: Touch .zprofile file
  ansible.builtin.file:
    path: "{{ user_home }}/.zprofile"
    state: touch
    mode: u=rwx
