- name: Install rofi
  ansible.builtin.command: nix profile install nixpkgs#rofi-wayland
  changed_when: false

- name: Create a rofi config directory if it does not exist
  ansible.builtin.file:
    path: "{{ user_home }}/.config/rofi"
    state: directory
    recurse: true

- name: Check if rofi config file exists
  ansible.builtin.stat:
    path: "{{ user_home }}/.config/rofi/config.rasi"
  register: has_rofi_config
  failed_when: false

- name: Backup rofi config file
  ansible.builtin.command: mv {{ user_home }}/.config/rofi/config.rasi {{ user_home }}/.config/rofi/config.rasi.bak
  when: has_rofi_config.stat.exists
  changed_when: false

- name: Symlink rofi config file
  ansible.builtin.file:
    src: "{{ role_path }}/files/config.rasi"
    dest: "{{ user_home }}/.config/rofi/config.rasi"
    state: link
