- name: Update the package cache
  become: true
  ansible.builtin.dnf:
    update_cache: true

- name: Upgrade existing packages
  become: true
  ansible.builtin.dnf:
    name: "*"
    state: latest
    update_only: true

- name: Installs common packages | dnf
  become: true
  ansible.builtin.dnf:
    name: "{{ common_packages }}"
    state: present

- name: Cleans packages | dnf
  become: true
  ansible.builtin.dnf:
    autoremove: true

- name: Set the default LANG
  become: true
  ansible.builtin.lineinfile:
    dest: /etc/locale.conf
    regexp: "^LANG="
    line: "LANG=C.UTF-8"
    state: present

- name: Set the default LANGUAGE
  become: true
  ansible.builtin.lineinfile:
    dest: /etc/locale.conf
    regexp: "^LANGUAGE="
    line: "LANGUAGE=C.UTF-8"
    state: present

- name: Set the default LC_ALL
  become: true
  ansible.builtin.lineinfile:
    dest: /etc/locale.conf
    regexp: "^LC_ALL="
    line: "LC_ALL=C.UTF-8"
    state: present

- name: Include nix
  ansible.builtin.import_tasks: nix.yml
