- name: Check if nix is installed
  ansible.builtin.command: nix-env --version
  register: nix_installed
  failed_when: false
  changed_when: false
  environment:
    PATH: "{{ ansible_env.PATH }}:/nix/var/nix/profiles/default/bin"

- name: Install nix
  ansible.builtin.shell:
    executable: /bin/bash
    cmd: |
      set -o pipefail # ansible-lint(risky-shell-pipe)
      curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | sh -s -- install --no-confirm
  when: nix_installed.rc != 0
  changed_when: false
