- name: Install apps
  loop: "{{ packages }}"
  ansible.builtin.command: "nix profile install nixpkgs#{{ item }}"
  changed_when: false

- name: Create a kanshi config folder
  ansible.builtin.file:
    path: "{{ user_home }}/.config/kanshi"
    state: directory
    mode: u=rwx

- name: Create a kanshi config file if it does not exist
  ansible.builtin.file:
    path: "{{ user_home }}/.config/kanshi/config"
    state: touch
    mode: u=rwx
