- name: Install neovim
  become: true
  ansible.builtin.dnf:
    name: neovim, python3-neovim
    state: present

- name: Symlink .vimrc
  ansible.builtin.file:
    src: "{{ role_path }}/files/.vimrc"
    dest: "{{ user_home }}/.vimrc"
    state: link

- name: Symlink nvim
  ansible.builtin.file:
    src: "{{ role_path }}/files/nvim"
    dest: "{{ user_home }}/.config/nvim"
    state: link

- name: Install tree-sitter-cli
  become: true
  ansible.builtin.dnf:
    name: tree-sitter-cli
    state: present
